# Generated by Django 5.2.7 on 2025-10-17 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organigramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pdf', models.FileField(max_length=255, upload_to='organigramme/')),
                ('fichier_avif', models.FileField(blank=True, editable=False, max_length=255, null=True, upload_to='organigramme/')),
                ('date_mise_a_jour', models.DateField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Organigramme',
                'verbose_name_plural': 'Organigramme',
            },
        ),
    ]
