# Generated by Django 5.2.7 on 2025-10-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pdf', models.FileField(max_length=255, upload_to='rapports_activite/')),
                ('fichier_avif', models.FileField(blank=True, editable=False, max_length=255, null=True, upload_to='rapports_activite/')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': "Rapport d'Activité",
                'verbose_name_plural': "Rapports d'Activité",
            },
        ),
    ]
