# Generated by Django 5.2.7 on 2025-10-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rapportactivite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapportactivite',
            name='fichier_avif',
        ),
    ]
