# Generated by Django 5.2.7 on 2025-10-30 09:44

import django.db.models.deletion
import django.utils.timezone
import newsletter.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date_derniere_publication', models.DateField(editable=False)),
                ('date_creation', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('contenu', models.TextField(blank=True, default='')),
                ('est_publie', models.BooleanField(default=False)),
                ('categorie', models.CharField(choices=[('ACTU', 'Actualité'), ('RPRESSE', 'Revue de presse'), ('RH', 'Info RH'), ('ADM', 'Administration générale'), ('OUTIL', 'Outil Interne'), ('SI', 'Info SI')], max_length=100)),
                ('image_en_tete', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('auteur', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_derniere_publication'],
                'permissions': [('peut_ecrire_actu', 'Peut écrire des actualités'), ('peut_ecrire_rpresse', 'Peut écrire des revues de presse'), ('peut_ecrire_rh', 'Peut écrire des articles RH'), ('peut_ecrire_adm', "Peut écrire des articles d'administration générale"), ('peut_ecrire_outil', "Peut écrire des articles d'outils interne"), ('peut_ecrire_si', 'Peut écrire des articles SI')],
            },
        ),
        migrations.CreateModel(
            name='CustomAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=newsletter.models.custom_attachment_upload_to)),
                ('est_utilisee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image Summernote',
                'verbose_name_plural': 'Images Summernote',
            },
        ),
        migrations.CreateModel(
            name='OutilInterne',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='newsletter.article')),
                ('lien_outil', models.URLField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Outil interne',
                'verbose_name_plural': 'Outils internes',
            },
            bases=('newsletter.article',),
        ),
    ]
