# Generated by Django 5.2.7 on 2025-10-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_derniere_publication',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
