"""
Django settings for intranetFA project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"


ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    # Apps par défaut :
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Mes Apps :
    "newsletter.apps.NewsletterConfig",
    "trombinoscope.apps.TrombinoscopeConfig",
    "fiche_reflexes.apps.FicheReflexesConfig",
    "core.apps.CoreConfig",
    # Pour la création d'article avec images et mise en forme :
    "django_summernote",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "intranetFA.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "intranetFA.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("PSQL_ENGINE"),
        "NAME": os.getenv("PSQL_DB_NAME"),
        "USER": os.getenv("PSQL_USER"),
        "PASSWORD": os.getenv("PSQL_PASSWORD"),
        "HOST": os.getenv("PSQL_HOST"),
        "PORT": os.getenv("PSQL_PORT"),
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-trombinoscope-cache",
    }
}


# Configuration LDAP
LDAP_SERVER_URI = os.getenv("LDAP_SERVER_URI")
LDAP_BASE_DN = os.getenv("LDAP_BASE_DN")
LDAP_EMAIL_DOMAIN = os.getenv("LDAP_EMAIL_DOMAIN")

# Compte de service AD
LDAP_BIND_DN = os.getenv("LDAP_BIND_DN")
LDAP_BIND_PASSWORD = os.getenv("LDAP_BIND_PASSWORD")

# Clé SSL
LOCAL_PRIVATE_KEY = os.getenv("LOCAL_PRIVATE_KEY")
LOCAL_CERTIFICATE = os.getenv("LOCAL_CERTIFICATE")


AUTHENTICATION_BACKENDS = [
    "core.services.auth_backends.LDAP3Backend",
    "django.contrib.auth.backends.ModelBackend",
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "FR"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": os.getenv("LOG_LEVEL", "INFO"),
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.getenv("LOG_FILE", "debug.log"),
            "formatter": "verbose",
            "maxBytes": int(os.getenv("LOG_MAX_BYTES", 1024 * 1024 * 5)),
            "backupCount": int(os.getenv("LOG_BACKUP_COUNT", 3)),
            "delay": True,
        },
        "console": {
            "level": os.getenv("LOG_LEVEL", "INFO"),
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": os.getenv("LOG_LEVEL", "INFO"),
        },
        "django.request": {
            "handlers": ["file", "console"],
            "level": "ERROR",
            "propagate": True,
        },
        "newsletter": {
            "handlers": ["console", "file"],
            "level": os.getenv("LOG_LEVEL_APP", "INFO"),
        },
        "core": {
            "handlers": ["console", "file"],
            "level": os.getenv("LOG_LEVEL_APP", "INFO"),
        },
        "trombinoscope": {
            "handlers": ["console", "file"],
            "level": os.getenv("LOG_LEVEL_APP", "INFO"),
        },
        "fiche_reflexes": {
            "handlers": ["console", "file"],
            "level": os.getenv("LOG_LEVEL_APP", "INFO"),
        },
    },
}

DATA_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024
# FILE_UPLOAD_MAX_MEMORY_SIZE =

SUMMERNOTE_CONFIG = {
    # On utilise notre modèle personnalisé pour diminuer la taille des images en mémoire
    "attachment_model": "newsletter.CustomAttachment",
    # Taille d'image max avant compression
    "attachment_filesize_limit": 20 * 1024 * 1024,
    "summernote": {
        "lang": "fr-FR",
        # Toolbar customization
        # https://summernote.org/deep-dive/#custom-toolbar-popover
        "toolbar": [
            ["style", ["style"]],
            ["style", ["bold", "italic", "underline", "clear"]],
            ["para", ["ul", "ol", "paragraph"]],
            ["color", ["color"]],
            ["table", ["table", "hr"]],
            ["insert", ["link", "picture"]],
            ["undo", ["undo", "redo"]],
            ["view", ["fullscreen", "codeview"]],
            ["help", ["help"]],
            # Autres options :
            # ['fontsize', ['fontsize']],
            # ["font", ["strikethrough", "superscript", "subscript"]],
            # ["fontname", ["fontname"]],
            # ["height", ["height"]],  # interligne
        ],
        "attachment_require_authentication": True,
        "styleTags": ["h1", "h2", "h3", "p"],
        # parametrage de la fonction éditeur de code 'codeview' :
        "codemirror": {
            "mode": "htmlmixed",
            "lineNumbers": "true",
            "theme": "monokai",
        },
        # protection XSS ! seulement pour le front !
        "codeviewFilter": "true",  # filtre les tags interdits en mode CodeView
        "codeviewIframeFilter": "true",  # n’autorise les iframes que de domaines whitelistés
    },
}

import django_summernote.settings as summernote_settings

summernote_settings.ATTACHMENT_MODEL = "newsletter.CustomAttachment"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
