# Generated by Django 5.2.7 on 2025-10-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_reflexes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichereflexes',
            options={'verbose_name': 'Fiche réflexes', 'verbose_name_plural': 'Fiches réflexes'},
        ),
        migrations.AddField(
            model_name='fichereflexes',
            name='fichier_avif',
            field=models.FileField(blank=True, null=True, upload_to='fiche_reflexes/'),
        ),
    ]
