# Generated by Django 5.2.7 on 2025-10-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_reflexes', '0002_alter_fichereflexes_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichereflexes',
            old_name='fichier',
            new_name='fichier_pdf',
        ),
    ]
