# Generated by Django 5.2.7 on 2025-10-10 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_reflexes', '0003_rename_fichier_fichereflexes_fichier_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichereflexes',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='fichereflexes',
            name='fichier_avif',
            field=models.FileField(blank=True, editable=False, max_length=255, null=True, upload_to='fiche_reflexes/'),
        ),
        migrations.AlterField(
            model_name='fichereflexes',
            name='fichier_pdf',
            field=models.FileField(max_length=255, upload_to='fiche_reflexes/'),
        ),
    ]
